# Generated by Django 4.1.1 on 2022-09-08 14:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampledatamodel',
            name='data',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
