# Generated by Django 4.1.1 on 2022-09-29 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='addresstable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streetNum', models.IntegerField()),
                ('streetName', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=25)),
                ('state', models.CharField(max_length=20)),
                ('parishId', models.IntegerField()),
                ('firstFloorHeight', models.FloatField()),
                ('floodLocation', models.FloatField()),
                ('floodScale', models.FloatField()),
            ],
        ),
    ]
