# Generated by Django 4.1.1 on 2022-09-15 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restApp', '0002_alter_sampledatamodel_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='testmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zipCode', models.IntegerField()),
                ('constructionCost', models.CharField(max_length=60)),
                ('movingCost', models.FloatField()),
                ('lodgingRate', models.FloatField()),
            ],
        ),
    ]
