# Generated by Django 4.1.1 on 2023-03-07 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restApp', '0004_addresstable_unitcost'),
    ]

    operations = [
        migrations.CreateModel(
            name='baseRateMultipliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('levee', models.CharField(max_length=10)),
                ('bi', models.CharField(max_length=10)),
                ('region', models.CharField(max_length=20)),
                ('segment', models.IntegerField()),
                ('singleFamilyHomeIndicator', models.CharField(max_length=10)),
                ('ifType', models.CharField(max_length=15)),
                ('ifBuilding', models.FloatField()),
                ('ifContents', models.FloatField()),
                ('ssBuilding', models.FloatField()),
                ('ssContents', models.FloatField()),
                ('tsuBuilding', models.FloatField()),
                ('tsuContents', models.FloatField()),
                ('glBuilding', models.FloatField()),
                ('glContents', models.FloatField()),
                ('ceBuilding', models.FloatField()),
                ('ceContents', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='distToCoastMultipliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('levee', models.CharField(max_length=10)),
                ('region', models.CharField(max_length=20)),
                ('bi', models.CharField(max_length=10)),
                ('dtc_meters', models.IntegerField()),
                ('ce', models.FloatField()),
                ('ss', models.FloatField()),
                ('tsu', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='distToLakeMultipliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('levee', models.CharField(max_length=10)),
                ('dtl_meters', models.IntegerField()),
                ('gl', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='distToOceanMultipliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('levee', models.CharField(max_length=10)),
                ('region', models.CharField(max_length=20)),
                ('bi', models.CharField(max_length=10)),
                ('dto_meters', models.IntegerField()),
                ('ss', models.FloatField()),
                ('tsu', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='distToRiverMultipliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('levee', models.CharField(max_length=10)),
                ('region', models.CharField(max_length=20)),
                ('dtr_meters', models.IntegerField()),
                ('ifvalue', models.FloatField()),
                ('ifType', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='drainageAreaMultipliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('levee', models.CharField(max_length=10)),
                ('region', models.CharField(max_length=20)),
                ('segment', models.IntegerField()),
                ('da_km2', models.IntegerField()),
                ('ifvalue', models.FloatField()),
                ('ifType', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='elevation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('levee', models.CharField(max_length=10)),
                ('bi', models.CharField(max_length=10)),
                ('region', models.CharField(max_length=20)),
                ('elevation_feet', models.IntegerField()),
                ('ifvalue', models.FloatField()),
                ('ifType', models.CharField(max_length=15)),
                ('ss', models.FloatField()),
                ('tsu', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='elevRelToLake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('levee', models.CharField(max_length=10)),
                ('erl_feet', models.FloatField()),
                ('gl', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='elevRelToRiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('levee', models.CharField(max_length=10)),
                ('region', models.CharField(max_length=20)),
                ('segment', models.IntegerField()),
                ('riverClass', models.CharField(max_length=20)),
                ('err_feet', models.IntegerField()),
                ('ifvalue', models.FloatField()),
                ('ifType', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='leveeQuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leveeSystemID', models.IntegerField()),
                ('probOfFailPrior', models.FloatField()),
                ('overtoppingReturnPeriod', models.IntegerField()),
                ('leveeQualityFactor', models.FloatField()),
                ('toBeProbOfFailPrior', models.FloatField()),
                ('toBeOvertoppingReturnPeriod', models.IntegerField()),
                ('toBeLeveeQualityFactor', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='structuralRelElevation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('levee', models.CharField(max_length=10)),
                ('region', models.CharField(max_length=20)),
                ('sre_feet', models.IntegerField()),
                ('ifvalue', models.FloatField()),
                ('ifType', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='territory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('levee', models.CharField(max_length=10)),
                ('leveeSystemID', models.IntegerField()),
                ('bi', models.CharField(max_length=10)),
                ('huc12', models.FloatField()),
                ('peril', models.CharField(max_length=10)),
                ('ratingFactors', models.FloatField()),
            ],
        ),
    ]
