# Generated by Django 4.1.1 on 2023-03-29 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restApp', '0005_baseratemultipliers_disttocoastmultipliers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='territory',
            name='leveeSystemID',
            field=models.DecimalField(decimal_places=0, max_digits=29),
        ),
    ]
