# Generated by Django 4.1.1 on 2023-04-18 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restApp', '0012_floorsofinterest_foundationtype_typeofuse'),
    ]

    operations = [
        migrations.CreateModel(
            name='buildingValue',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('value', models.IntegerField()),
                ('allExclCE', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='contentsValue',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('value', models.IntegerField()),
                ('allExclCE', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='firstFloorHeight',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('height', models.IntegerField()),
                ('openNoObstructionWFV', models.FloatField()),
                ('openNoObstructionWbyFV', models.FloatField()),
                ('openObstructionWFV', models.FloatField()),
                ('openObstructionWbyFV', models.FloatField()),
                ('closedWallWFV', models.FloatField()),
                ('closedWallWbyFV', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MEAboveFirstFloor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('machineryEquipmentAboveFirstFloor', models.CharField(max_length=10)),
                ('coastalErosion', models.FloatField()),
            ],
        ),
    ]
