# Generated by Django 4.1.1 on 2023-04-24 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restApp', '0014_deductibleitvcova_deductibleitvcovc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='concentrationRisk',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('MSA', models.FloatField()),
                ('concentrationRiskTerritoryDescription', models.FloatField()),
                ('flood', models.FloatField()),
                ('surge', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='concentrationRiskMapping',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=30)),
                ('county', models.CharField(max_length=50)),
                ('concentrationRiskTerritory', models.CharField(max_length=10)),
            ],
        ),
    ]
