# Generated by Django 4.1.1 on 2023-04-24 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restApp', '0015_concentrationrisk_concentrationriskmapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concentrationrisk',
            name='MSA',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='concentrationrisk',
            name='concentrationRiskTerritoryDescription',
            field=models.CharField(max_length=100),
        ),
    ]
