# Generated by Django 4.1.1 on 2023-06-01 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restApp', '0019_alter_numofstories_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='homeShape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
            ],
        ),
    ]
