# Generated by Django 4.1.1 on 2023-06-01 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restApp', '0020_homeshape'),
    ]

    operations = [
        migrations.CreateModel(
            name='foundationTypeID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='scenario',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=200, null=True)),
                ('livableArea', models.FloatField(null=True)),
                ('floor', models.IntegerField(null=True)),
                ('annualFloodRisk', models.FloatField(null=True)),
                ('buildingCoverage', models.IntegerField(null=True)),
                ('buildingDeductible', models.IntegerField(null=True)),
                ('contentsCoverage', models.IntegerField(null=True)),
                ('contentsDeductible', models.IntegerField(null=True)),
                ('homeEquityLoanInterestRate', models.FloatField(null=True)),
                ('homeEquityLoanPeriod', models.IntegerField(null=True)),
                ('mortgageInterestRate', models.FloatField(null=True)),
                ('mortgagePeriod', models.IntegerField(null=True)),
                ('multiplierVersion', models.IntegerField(null=True)),
                ('userID', models.IntegerField(null=True)),
                ('levee', models.BooleanField(null=True)),
                ('leveeID', models.CharField(max_length=100, null=True)),
                ('leveeQuality', models.FloatField(null=True)),
                ('state', models.CharField(max_length=10, null=True)),
                ('stateLongName', models.CharField(max_length=50, null=True)),
                ('county', models.CharField(max_length=100, null=True)),
                ('fips', models.CharField(max_length=50, null=True)),
                ('segment', models.CharField(max_length=20, null=True)),
                ('concentrationRiskMapping', models.CharField(max_length=50, null=True)),
                ('HUC12', models.CharField(max_length=100, null=True)),
                ('barrierIslandIndicator', models.BooleanField(null=True)),
                ('baseRatePer1000ofCoverageValue', models.FloatField(null=True)),
                ('MSA', models.CharField(max_length=50, null=True)),
                ('distToRiver', models.FloatField(null=True)),
                ('riverFloodDepth', models.FloatField(null=True)),
                ('riverClass', models.CharField(max_length=50, null=True)),
                ('elevRelToRiver', models.FloatField(null=True)),
                ('drainageArea', models.FloatField(null=True)),
                ('strRelElev', models.FloatField(null=True)),
                ('distToCoast', models.FloatField(null=True)),
                ('distToOcean', models.FloatField(null=True)),
                ('elevation', models.FloatField(null=True)),
                ('distToLake', models.FloatField(null=True)),
                ('elevRelToLake', models.FloatField(null=True)),
                ('federalAssistanceID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restApp.federalassistance')),
                ('floodInsuranceID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restApp.floodinsurance')),
                ('foundationDesignID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restApp.foundationdesignid')),
                ('foundationTypeID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restApp.foundationtypeid')),
                ('homeConditionID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restApp.homecondition')),
                ('homeShapeID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restApp.homeshape')),
                ('investmentTypeID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restApp.investmenttype')),
                ('mortgageID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restApp.mortgage')),
                ('numOfStoriesID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restApp.numofstories')),
                ('priorClaimsID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restApp.priorclaims')),
                ('typeUseID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restApp.typeuseid')),
                ('userTypeID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restApp.usertypeid')),
            ],
        ),
    ]
