# Generated by Django 4.1.7 on 2023-06-16 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restApp', '0025_rename_barrierislandindicator_barrierislandindicators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='barrierIslandIndicator',
            field=models.BooleanField(null=True),
        ),
    ]
