# Generated by Django 4.1.7 on 2023-06-16 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restApp', '0026_alter_scenario_barrierislandindicator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='barrierIslandIndicator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='restApp.barrierislandindicators'),
        ),
    ]
