# Generated by Django 4.1.7 on 2023-07-03 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restApp', '0037_typeofuse_condounitownerindicatorid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeofuse',
            name='flood',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='typeofuse',
            name='lakes',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='typeofuse',
            name='surge',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='typeofuse',
            name='tsunami',
            field=models.FloatField(null=True),
        ),
    ]
