# Generated by Django 4.1.7 on 2023-07-04 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restApp', '0051_floor1to100_floor1to3_floor1to4'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='floor1to100ID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='restApp.floor1to100'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='floor1to3ID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='restApp.floor1to3'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='floor1to4ID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='restApp.floor1to4'),
        ),
    ]
