# Generated by Django 4.1.7 on 2023-07-05 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restApp', '0052_scenario_floor1to100id_scenario_floor1to3id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scenario',
            name='floorID',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='numOfStoriesID',
        ),
    ]
