# Generated by Django 4.1.7 on 2023-07-11 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restApp', '0054_rename_buildingvalue_scenario_buildingreplacementvalue_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scenario',
            name='annualFloodRisk',
        ),
    ]
