# Generated by Django 4.1.7 on 2023-07-11 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restApp', '0055_remove_scenario_annualfloodrisk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scenario',
            name='homeShapeID',
        ),
    ]
