# Generated by Django 4.1.1 on 2022-09-29 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restApp', '0002_addresstable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unitcost',
            name='id',
        ),
        migrations.AlterField(
            model_name='unitcost',
            name='zipCode',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
