# Generated by Django 4.1.1 on 2022-09-29 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restApp', '0003_remove_unitcost_id_alter_unitcost_zipcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='addresstable',
            name='unitCost',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restApp.unitcost'),
        ),
    ]
