# Generated by Django 4.1.1 on 2023-03-30 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restApp', '0007_alter_baseratemultipliers_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='riskrating2results',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('items', models.CharField(max_length=50)),
                ('inlandFloodBuldings', models.FloatField()),
                ('inlandFloodContents', models.FloatField()),
                ('stormSurgeBuldings', models.FloatField()),
                ('stormSurgeContents', models.FloatField()),
                ('psunamiBuldings', models.FloatField()),
                ('psunamiContents', models.FloatField()),
                ('greatLakesBuldings', models.FloatField()),
                ('greatLakesContents', models.FloatField()),
                ('coastalErosonBuldings', models.FloatField()),
                ('coastalErosonContents', models.FloatField()),
                ('allPerilsAllCoverage', models.FloatField()),
            ],
        ),
    ]
