# Generated by Django 4.1.1 on 2023-03-30 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restApp', '0009_rename_psunamibuldings_riskrating2results_tsunamibuldings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskrating2results',
            name='allPerilsAllCoverage',
            field=models.FloatField(null=True),
        ),
    ]
