# Generated by Django 4.1.1 on 2023-04-12 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restApp', '0010_alter_riskrating2results_allperilsallcoverage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskrating2results',
            name='coastalErosonBuldings',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='riskrating2results',
            name='coastalErosonContents',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='riskrating2results',
            name='greatLakesBuldings',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='riskrating2results',
            name='greatLakesContents',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='riskrating2results',
            name='inlandFloodBuldings',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='riskrating2results',
            name='inlandFloodContents',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='riskrating2results',
            name='stormSurgeBuldings',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='riskrating2results',
            name='stormSurgeContents',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='riskrating2results',
            name='tsunamiBuldings',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='riskrating2results',
            name='tsunamiContents',
            field=models.FloatField(null=True),
        ),
    ]
