# Generated by Django 4.1.1 on 2023-04-19 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restApp', '0013_buildingvalue_contentsvalue_firstfloorheight_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='deductibleITVCovA',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('coverageValueRatio', models.FloatField()),
                ('inlandFlood', models.FloatField()),
                ('SSTsunamiGreatLakesCoastalErosion', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='deductibleITVCovC',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('coverageValueRatio', models.FloatField()),
                ('inlandFlood', models.FloatField()),
                ('SSTsunamiGreatLakesCoastalErosion', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='deductibleLimitITVCovA',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('coverageValueRatio', models.FloatField()),
                ('inlandFlood', models.FloatField()),
                ('SSTsunamiGreatLakesCoastalErosion', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='deductibleLimitITVCovC',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('coverageValueRatio', models.FloatField()),
                ('inlandFlood', models.FloatField()),
                ('SSTsunamiGreatLakesCoastalErosion', models.FloatField()),
            ],
        ),
    ]
