# Generated by Django 4.1.1 on 2023-05-18 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restApp', '0016_alter_concentrationrisk_msa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='riskrating2resultsLevee',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('items', models.CharField(max_length=50)),
                ('inlandFloodFluvialBuldings', models.FloatField(null=True)),
                ('inlandFloodFluvialContents', models.FloatField(null=True)),
                ('inlandFloodPluvialBuldings', models.FloatField(null=True)),
                ('inlandFloodPluvialContents', models.FloatField(null=True)),
                ('stormSurgeBuldings', models.FloatField(null=True)),
                ('stormSurgeContents', models.FloatField(null=True)),
                ('tsunamiBuldings', models.FloatField(null=True)),
                ('tsunamiContents', models.FloatField(null=True)),
                ('greatLakesBuldings', models.FloatField(null=True)),
                ('greatLakesContents', models.FloatField(null=True)),
                ('coastalErosonBuldings', models.FloatField(null=True)),
                ('coastalErosonContents', models.FloatField(null=True)),
                ('allPerilsAllCoverage', models.FloatField(null=True)),
            ],
        ),
    ]
