# Generated by Django 4.1.1 on 2023-05-31 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restApp', '0018_federalassistance_floodinsurance_foundationdesignid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numofstories',
            name='Name',
            field=models.CharField(max_length=30),
        ),
    ]
