# Generated by Django 4.1.7 on 2023-06-16 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restApp', '0022_alter_scenario_barrierislandindicator'),
    ]

    operations = [
        migrations.CreateModel(
            name='barrierIslandIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='scenario',
            name='barrierIslandIndicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restApp.barrierislandindicator'),
        ),
    ]
