# Generated by Django 4.1.7 on 2023-06-16 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restApp', '0024_alter_scenario_barrierislandindicator'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='barrierIslandIndicator',
            new_name='barrierIslandIndicators',
        ),
    ]
