# Generated by Django 4.1.7 on 2023-06-21 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restApp', '0028_condounitownerindicator_floodvents_mande_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='MandEID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='restApp.mande'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='condoUnitOwnerIndicatorID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='restApp.condounitownerindicator'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='floodVentsID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='restApp.floodvents'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='primaryResidenceIndicatorID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='restApp.primaryresidenceindicator'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='singleFamilyHomeIndicatorID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='restApp.singlefamilyhomeindicator'),
        ),
    ]
