# Generated by Django 4.1.7 on 2023-06-21 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restApp', '0029_scenario_mandeid_scenario_condounitownerindicatorid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='buildingValue',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='scenario',
            name='contentsValue',
            field=models.IntegerField(null=True),
        ),
    ]
