# Generated by Django 4.1.7 on 2023-07-01 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restApp', '0032_scenario_condounitownerindicatorid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CRSrating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Value', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='scenario',
            name='crsRating',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='restApp.crsrating'),
        ),
    ]
