# Generated by Django 4.1.7 on 2023-07-03 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restApp', '0036_remove_scenario_floor_scenario_floorid'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeofuse',
            name='condoUnitOwnerIndicatorID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='restApp.condounitownerindicator'),
        ),
        migrations.AddField(
            model_name='typeofuse',
            name='singleFamilyHomeIndicatorID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='restApp.singlefamilyhomeindicator'),
        ),
    ]
