# Generated by Django 4.1.7 on 2023-07-03 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restApp', '0038_alter_typeofuse_flood_alter_typeofuse_lakes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scenario',
            name='typeUseID',
        ),
        migrations.AddField(
            model_name='scenario',
            name='typeOfUseID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='restApp.typeofuse'),
        ),
    ]
