# Generated by Django 4.1.7 on 2023-07-03 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restApp', '0039_remove_scenario_typeuseid_scenario_typeofuseid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='typeOfUseID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='restApp.typeuseid'),
        ),
    ]
