# Generated by Django 4.1.7 on 2023-07-03 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restApp', '0041_typeuseid_condounitownerindicatorid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typeuseid',
            name='condoUnitOwnerIndicatorID',
        ),
        migrations.RemoveField(
            model_name='typeuseid',
            name='singleFamilyHomeIndicatorID',
        ),
    ]
