# Generated by Django 4.1.7 on 2023-07-03 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restApp', '0046_rename_usertypeid_usertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertype',
            name='primaryResidenceIndicatorID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='restApp.primaryresidenceindicator'),
        ),
    ]
