# Generated by Django 4.1.7 on 2023-07-03 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restApp', '0047_usertype_primaryresidenceindicatorid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scenario',
            name='condoUnitOwnerIndicatorID',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='primaryResidenceIndicatorID',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='singleFamilyHomeIndicatorID',
        ),
    ]
