# Generated by Django 4.1.7 on 2023-07-03 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restApp', '0049_scenario_firstfloorheight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scenario',
            name='foundationDesignID',
        ),
    ]
