# Generated by Django 4.1.7 on 2023-07-05 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restApp', '0053_remove_scenario_floorid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scenario',
            old_name='buildingValue',
            new_name='buildingReplacementValue',
        ),
        migrations.RenameField(
            model_name='scenario',
            old_name='contentsValue',
            new_name='contentsReplacementValue',
        ),
    ]
