# Generated by Django 4.1.7 on 2023-07-11 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restApp', '0056_remove_scenario_homeshapeid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scenario',
            name='mortgageID',
        ),
    ]
