# Generated by Django 4.1.7 on 2023-07-24 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restApp', '0058_alter_scenario_floor1to100id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='stateAbbreviation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=50)),
                ('abbreviation', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='scenario',
            name='lattitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='scenario',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
