# Generated by Django 4.1.7 on 2023-07-26 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restApp', '0061_scenario_homeshapeid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='homeShapeID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='restApp.homeshape'),
        ),
    ]
