# Generated by Django 4.1.7 on 2023-07-26 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restApp', '0064_alter_scenario_homeshapeid'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='mortgageID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='restApp.mortgage'),
        ),
    ]
