# Generated by Django 4.1.7 on 2023-07-26 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restApp', '0065_scenario_mortgageid'),
    ]

    operations = [
        migrations.CreateModel(
            name='leveeIndicators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='scenario',
            name='levee',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='restApp.leveeindicators'),
        ),
    ]
