# Generated by Django 4.1.7 on 2023-08-01 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restApp', '0066_leveeindicators_alter_scenario_levee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stateabbreviation',
            name='abbreviation',
            field=models.CharField(max_length=10),
        ),
    ]
