# Generated by Django 4.1.7 on 2023-08-01 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restApp', '0067_alter_stateabbreviation_abbreviation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scenario',
            old_name='riverFloodDepth',
            new_name='floodDepthDifference',
        ),
    ]
