# Generated by Django 4.1.7 on 2023-08-17 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restApp', '0068_rename_riverflooddepth_scenario_flooddepthdifference'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='freeboard',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
