# Generated by Django 4.1.7 on 2023-08-21 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restApp', '0069_scenario_freeboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='BFE',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='scenario',
            name='floodZone',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
