# Generated by Django 4.1.7 on 2023-08-25 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restApp', '0070_scenario_bfe_scenario_floodzone'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='returnPeriod100Y',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='scenario',
            name='returnPeriod10Y',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='scenario',
            name='returnPeriod200Y',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='scenario',
            name='returnPeriod20Y',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='scenario',
            name='returnPeriod250Y',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='scenario',
            name='returnPeriod500Y',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='scenario',
            name='returnPeriod50Y',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='scenario',
            name='returnPeriod5Y',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='scenario',
            name='returnPeriod75Y',
            field=models.IntegerField(null=True),
        ),
    ]
