# Generated by Django 4.1.7 on 2023-08-25 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restApp', '0071_scenario_returnperiod100y_scenario_returnperiod10y_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='returnPeriod100Y',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='returnPeriod10Y',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='returnPeriod200Y',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='returnPeriod20Y',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='returnPeriod250Y',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='returnPeriod500Y',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='returnPeriod50Y',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='returnPeriod5Y',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='returnPeriod75Y',
            field=models.FloatField(null=True),
        ),
    ]
