# Generated by Django 4.1.7 on 2023-08-25 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restApp', '0073_scenario_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='firstFloorHeight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
