# Generated by Django 4.1.7 on 2023-08-28 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restApp', '0074_alter_scenario_firstfloorheight'),
    ]

    operations = [
        migrations.CreateModel(
            name='ddfBuildingNobase1AAE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depth', models.FloatField()),
                ('associatedDamage', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ddfBuildingNobase2AAE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depth', models.FloatField()),
                ('associatedDamage', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ddfBuildingWithObsVVE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depth', models.FloatField()),
                ('associatedDamage', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ddfBuildingWithoutObsVVE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depth', models.FloatField()),
                ('associatedDamage', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ddfContentsNobase1AAE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depth', models.FloatField()),
                ('associatedDamage', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ddfContentsNobase2AAE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depth', models.FloatField()),
                ('associatedDamage', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ddfContentsWithObsVVE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depth', models.FloatField()),
                ('associatedDamage', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ddfContentsWithoutObsVVE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depth', models.FloatField()),
                ('associatedDamage', models.FloatField()),
            ],
        ),
    ]
