# Generated by Django 4.1.7 on 2023-08-28 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restApp', '0075_ddfbuildingnobase1aae_ddfbuildingnobase2aae_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='numOfStoriesID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='restApp.numofstories'),
        ),
    ]
