# Generated by Django 4.1.7 on 2023-08-28 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restApp', '0076_scenario_numofstoriesid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='numOfStoriesID',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='restApp.numofstories'),
        ),
    ]
