# Generated by Django 4.1.7 on 2023-08-28 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restApp', '0077_alter_scenario_numofstoriesid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scenario',
            name='numOfStoriesID',
        ),
    ]
